version: '3'

services:
  ebac-postgres-compose:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "123456"
    ports:
      - "15432:5432"
    volumes:
      - \\wsl$\docker-desktop-data\version-pack-data\community\docker\volumes
    networks:
      - postgres-ebac-network

  ebac-pgadmin-compose:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "jeb@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "123456"
    ports:
      - "16543:80"
    depends_on:
      - ebac-postgres-compose
    networks:
      - postgres-ebac-network

#  ebac-mysql-compose:
#    image: mysql/mysql-server:latest
#    environment:
#      MYSQL_ROOT_PASSWORD: "admin"
#      MYSQL_DATABASE: 'vendas_online'
#      MYSQL_USER: 'admin'
#      MYSQL_PASSWORD: 'admin'
#    ports:
#      - "3306:3306"

networks:
  postgres-ebac-network:
    driver: bridge